import json
from elasticsearch import Elasticsearch
from indexa import connect_elasticsearch


def multi_match_grid_search(
    es: Elasticsearch, query, sw: bool, proc: str, sim: str, skip=0, size=5
):
    """Searches a specific index configuration generated by the grid search."""
    index_name = f"hqs_sw_{'yes' if sw else 'no'}_proc_{proc}_sim_{sim}"

    res = es.search(
        index=index_name,
        body={
            "query": {
                "multi_match": {
                    "query": query,
                    "fields": ["issue_title^2", "issue_description", "comic_name^3"],
                    "type": "best_fields",
                }
            },
        },
        from_=skip,
        size=size,
    )
    return res


def run_full_grid_evaluation(es: Elasticsearch, search_query: str):
    """Executes the query across all 18 configurations to cross-examine top score profiles."""
    import itertools

    sw_options = [True, False]
    proc_options = ["none", "stemming", "lemmatization"]
    sim_options = ["bm25", "jelinek_mercer", "dirichlet"]

    print(f"\nAVALIANDO QUERY: '{search_query}' ATRAVÉS DO GRID SEARCH")
    print(
        f"{'CONFIGURAÇÃO':<45} | {'MAX SCORE':<10} | {'TOP HIT ID':<10}"
    )
    print("-" * 75)

    for sw, proc, sim in itertools.product(
        sw_options, proc_options, sim_options
    ):
        cfg_desc = f"SW:{str(sw):<5} | Proc:{proc:<13} | Sim:{sim:<14}"

        try:
            res = multi_match_grid_search(
                es, search_query, sw, proc, sim, size=1
            )
            hits = res["hits"]["hits"]

            if hits:
                max_score = round(res["hits"]["max_score"], 4)
                top_hit_id = hits[0]["_id"]
                print(f"{cfg_desc} | {max_score:<10} | {top_hit_id:<10}")
            else:
                print(f"{cfg_desc} | Sem resultados")
        except Exception as e:
            print(f"{cfg_desc} | Erro ao buscar: {e}")


def main():
    es = connect_elasticsearch()

    # Exemplo 1: Buscar diretamente em uma combinação específica do Grid Search
    # (Remoção de stopword=Sim, Lemarização=Sim, Modelo LM Dirichlet)
    print("\n--- BUSCA EM CONFIGURAÇÃO ÚNICA ESPECÍFICA ---")
    resultado_unico = multi_match_grid_search(
        es, query="thor #1", sw=True, proc="lemmatization", sim="dirichlet"
    )
    print(
        f"Total de hits na config escolhida: {resultado_unico['hits']['total']['value']}"
    )

    # Exemplo 2: Executar análise comparativa macro de resultados de uma query
    # print("\n--- EXECUÇÃO COMPARATIVA EM TODO O GRID ---")
    # run_full_grid_evaluation(es, "thor #1")


if __name__ == "__main__":
    main()